
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [9]:
import numpy as np

arr = np.arange(10)


print(arr)


[0 1 2 3 4 5 6 7 8 9]


Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [32]:
import numpy as np
arr = np.arange(9)
shaped = arr.reshape(3,3)
print(shaped)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Access the element at the second row, second column.


In [33]:
element = shaped[1, 1]
print("Element at (1, 1):", element)

Element at (1, 1): 4


Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [34]:
np.add([1, 2, 3], [4, 5, 6])

array([5, 7, 9])

In [36]:
np.subtract( [1, 2, 3],[4, 5, 6])

array([-3, -3, -3])

In [37]:
np.multiply([1, 2, 3], [4, 5, 6])

array([ 4, 10, 18])

In [38]:
np.divide([1, 2, 3],[4, 5, 6])

array([0.25, 0.4 , 0.5 ])

Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [39]:
np.mean([1, 2, 3, 4, 5])

3.0

In [40]:
np.sum([1, 2, 3, 4, 5])

15

In [41]:
np.std([1, 2, 3, 4, 5])

1.4142135623730951

Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [43]:

original_array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = original_array.reshape((2, 3))

print(reshaped_array)

[[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [44]:

random = np.random.random((5, 5))

print("Random Array:")
print(random)


Random Array:
[[0.72776444 0.7609846  0.69572203 0.31709478 0.13663269]
 [0.91453026 0.94140699 0.34246757 0.057609   0.38699859]
 [0.59891549 0.23818676 0.38586356 0.23965492 0.11976588]
 [0.32972594 0.0270366  0.22636139 0.53874203 0.80982882]
 [0.34212896 0.4807931  0.56375104 0.30642958 0.373031  ]]


Replace all values in the sub-array with a specific value.


In [46]:

original = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sub_array = (1, slice(None))

original[sub_array] = 10

print("Modified Array:")
print(original)


Modified Array:
[[ 1  2  3]
 [10 10 10]
 [ 7  8  9]]


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [47]:

original = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
subarray = original[1:3, :]
print(subarray)


[[3 4]
 [5 6]]



# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [48]:

array_2d = np.array([[0, 1, 2],
                     [0, 1, 2],
                     [0, 1, 2]])

print(array_2d)

[[0 1 2]
 [0 1 2]
 [0 1 2]]


Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [49]:

array_2d = np.array([[0, 1, 2],
                     [0, 1, 2],
                     [0, 1, 2]])

array_1d = np.array([3, 4, 5])

result = array_2d + array_1d[:, np.newaxis]

print(result)


[[3 4 5]
 [4 5 6]
 [5 6 7]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [50]:

array1 = np.random.randint(10, size=(3, 3))
array2 = np.random.randint(10, size=(3, 3))

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)


Array 1:
[[4 1 2]
 [2 1 8]
 [2 5 9]]

Array 2:
[[5 1 3]
 [9 7 2]
 [8 8 7]]


In [53]:

horizontal_concatenation = np.hstack((array1, array2))

print("Horizontal Concatenation:")
print(horizontal_concatenation)
vertical_concatenation = np.vstack((array1, array2))

print("\nVertical Concatenation:")
print(vertical_concatenation)


Horizontal Concatenation:
[[4 1 2 5 1 3]
 [2 1 8 9 7 2]
 [2 5 9 8 8 7]]

Vertical Concatenation:
[[4 1 2]
 [2 1 8]
 [2 5 9]
 [5 1 3]
 [9 7 2]
 [8 8 7]]


In [54]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [57]:

arr = np.array([1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5])

vals, counts = np.unique(arr, return_counts=True)

mode_indices = np.argwhere(counts == np.max(counts))

mode_values = vals[mode_indices]

print("Mode value(s):", mode_values.flatten())


Mode value(s): [1]


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

